/*******************************************************************************
 * Steven Tang
 * Instructor.cpp
 * May 9, 2015
 * This .cpp file defines all the functions that are in Instructor.h.
 * It sets the salary to s, as well as setting it to 0.
 * The print function prints out whether the individual is a male or female and then
 * prints out the salary that he or she has. I used ArgoUML to get the "Skeleton" of the code.
 * 100% Complete
 *******************************************************************************/
#include <iostream>
#include "Instructor.h"

using namespace std;

Instructor::Instructor(): Person(), salary(0)
// don't delete the following line as it's needed to preserve source code of this autogenerated element
// section -64--88-0-5--7675e75b:14d3b25e278:-8000:000000000000087A begin
{
    salary = 0;
}
// section -64--88-0-5--7675e75b:14d3b25e278:-8000:000000000000087A end
// don't delete the previous line as it's needed to preserve source code of this autogenerated element

Instructor::Instructor(string n, string d, string g, int s): Person(n, d, g), salary(s)
// don't delete the following line as it's needed to preserve source code of this autogenerated element
// section -64--88-0-5--7675e75b:14d3b25e278:-8000:000000000000087E begin
{
    salary = s;
}
// section -64--88-0-5--7675e75b:14d3b25e278:-8000:000000000000087E end
// don't delete the previous line as it's needed to preserve source code of this autogenerated element

void Instructor::print()
// don't delete the following line as it's needed to preserve source code of this autogenerated element
// section -64--88-0-5--7675e75b:14d3b25e278:-8000:0000000000000884 begin
{
    if (gender == "M")
        cout << "Mr. ";
    else // assuming gender == "F"
        cout << "Ms. ";
    Person::print();
    cout << "    Instructor, Salary: " << salary << endl;
}
// section -64--88-0-5--7675e75b:14d3b25e278:-8000:0000000000000884 end
// don't delete the previous line as it's needed to preserve source code of this autogenerated element
