/*******************************************************************************
 * Steven Tang
 * Person.cpp
 * May 9, 2015
 * In this .cpp file, we have the defined functions that was listed in Person.h
 * Name, gender, and dob is set to a null value. They are also set to n, g, and d.
 * The print function prints out the information that is in the main function. I used ArgoUML to get the "Skeleton" of
 * the code.
 * 100% Complete
 *******************************************************************************/
#include <iostream>
#include "Person.h"

using namespace std;

Person::Person()
// don't delete the following line as it's needed to preserve source code of this autogenerated element
// section -64--88-0-5--7675e75b:14d3b25e278:-8000:0000000000000886 begin
{
 name = "";
 gender= "";
 dob = "";
}
// section -64--88-0-5--7675e75b:14d3b25e278:-8000:0000000000000886 end
// don't delete the previous line as it's needed to preserve source code of this autogenerated element

Person::Person(string n, string d, string g)// don't delete the following line as it's needed to preserve source code of this autogenerated element
// section -64--88-0-5--7675e75b:14d3b25e278:-8000:0000000000000888 begin
{
    name = n;
    gender = g;
    dob = d;
}
// section -64--88-0-5--7675e75b:14d3b25e278:-8000:0000000000000888 end
// don't delete the previous line as it's needed to preserve source code of this autogenerated element

void Person::print()
// don't delete the following line as it's needed to preserve source code of this autogenerated element
// section -64--88-0-5--7675e75b:14d3b25e278:-8000:000000000000088D begin
{
    cout << name << " " << dob << endl;
}
// section -64--88-0-5--7675e75b:14d3b25e278:-8000:000000000000088D end
// don't delete the previous line as it's needed to preserve source code of this autogenerated element
