/*******************************************************************************
 * Steven Tang
 * Student.cpp
 * May 9, 2015
 * In this .cpp file we declare all the functions that was listed in Student.h.
 * We set major to null so it isn't set to anything and we also set it to m.
 * All the print function does is print out the student's major. I used ArgoUML to get the "Skeleton" of
 * the code.
 * 100% Complete 
 *******************************************************************************/
#include "Student.h"
#include <iostream>

using namespace std;

Student::Student()
// don't delete the following line as it's needed to preserve source code of this autogenerated element
// section -64--88-0-5--7675e75b:14d3b25e278:-8000:000000000000088F begin
{
    major = "";
}
// section -64--88-0-5--7675e75b:14d3b25e278:-8000:000000000000088F end
// don't delete the previous line as it's needed to preserve source code of this autogenerated element

Student::Student(string n, string d, string g, string m): Person(n, d, g), major(m)
// don't delete the following line as it's needed to preserve source code of this autogenerated element
// section -64--88-0-5--7675e75b:14d3b25e278:-8000:0000000000000895 begin
{
    major = m;
}
// section -64--88-0-5--7675e75b:14d3b25e278:-8000:0000000000000895 end
// don't delete the previous line as it's needed to preserve source code of this autogenerated element

void Student::print()
// don't delete the following line as it's needed to preserve source code of this autogenerated element
// section -64--88-0-5--7675e75b:14d3b25e278:-8000:000000000000089B begin
{
    Person::print();
    cout << "    Student, Major: " << major << endl;
}
// section -64--88-0-5--7675e75b:14d3b25e278:-8000:000000000000089B end
// don't delete the previous line as it's needed to preserve source code of this autogenerated element
